name: stella

networks:
  stella-shared:
    external: true
    name: stella-shared

services:
    search:
        build: ./app
        volumes:
          - ./data/:/data/
        ports:
            - "8888:5000"
        networks:
          - stella-shared 